[package]
name = "dolly"
version = "0.1.3"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Composable camera rigs"
repository = "https://github.com/h3r2tic/dolly"
documentation = "https://docs.rs/dolly"
keywords = ["gamedev", "camera", "3d"]
categories = ["game-development"]
readme = "crates-io.md"

[dependencies]
glam = ">=0.15, <=0.18"
dolly_derive = { path = "dolly_derive" }

[dev-dependencies]
macroquad = "0.3"